# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' List the avaialble model configurations
#'
#' @return List of available model configurations
#' @export
list_model_configurations <- function() {
    .Call(`_frogger_list_model_configurations`)
}

run_base_model <- function(parameters, configuration, output_years) {
    .Call(`_frogger_run_base_model`, parameters, configuration, output_years)
}

run_base_model_from_state <- function(parameters, configuration, initial_state, simulation_start_year, output_years) {
    .Call(`_frogger_run_base_model_from_state`, parameters, configuration, initial_state, simulation_start_year, output_years)
}

run_base_model_single_year <- function(parameters, configuration, initial_state, simulation_start_year) {
    .Call(`_frogger_run_base_model_single_year`, parameters, configuration, initial_state, simulation_start_year)
}

