#!/usr/bin/env Rscript

pkgload::load_all(here::here())
frogger:::generate_input_interface(dest = "inst/r_interface/model_input.hpp")
frogger:::generate_output_interface(dest = "inst/r_interface/model_output.hpp")
