#!/usr/bin/env Rscript

## Run this if you want to recreate the test data for the standalone model.
## You might do this is say we add some new required data or if the data we are testing with
## changes for any reason

repo_root <- gert::git_find()
configs_dir <- file.path(repo_root, "cpp_generation/modelSchemas/configs")
save_root_dir <- file.path(repo_root, "inst/standalone_model/data")

write_standalone_data <- function(input_data, data_map, dest) {
  t <- tempfile()
  dir.create(t)

  ## Basepop handled separately as we only save a slice of this out
  frogger:::serialize_r_to_tensor(demp$basepop[, , 1],
                                  file.path(t, "demography_base_pop"))
  for (r_name in setdiff(names(data_map), "basepop")) {
    frogger:::serialize_r_to_tensor(input_data[[r_name]], file.path(t, data_map[[r_name]]))
  }
  o <- zip::zip(dest,
                list.files(t, full.names = TRUE),
                include_directories = FALSE,
                root = save_root_dir,
                mode = "cherry-pick")
  file.path(save_root_dir, o)
}

build_name_mapping <- function() {
  cfgs <- list.files(configs_dir, full.names = TRUE)
  all_params <- lapply(cfgs, function(cfg) {
    params <- jsonlite::read_json(cfg)$pars
    lapply(params, function(param) {
      param$alias$r
    })
  })
  all_params <- unlist(all_params)
  setNames(names(all_params), all_params)
}

## Map from name in demp/parameters to name expected in C++ code
name_mapping <- build_name_mapping()

demp <- readRDS(testthat::test_path("testdata/demographic_projection_object_adult.rds"))
parameters <- readRDS(testthat::test_path("testdata/projection_parameters_adult.rds"))
input_data <- c(demp, parameters)
input_data$cd4_initdist <- input_data[["cd4_initdist_full"]]
input_data$cd4_prog <- input_data[["cd4_prog_full"]]
input_data$cd4_mort <- input_data[["cd4_mort_full"]]
input_data$art_mort <- input_data[["art_mort_full"]]

path <- write_standalone_data(input_data, name_mapping, "adult_data.zip")
message(sprintf("Wrote adult test data to %s", path))

source(file.path("R", "spectrum_inputs.R"))
child <- readRDS(testthat::test_path("testdata/child_parms.rds"))
input_data <- c(child$demp, child$parameters)
input_data$cd4_initdist <- input_data[["cd4_initdist_full"]]
input_data$cd4_prog <- input_data[["cd4_prog_full"]]
input_data$cd4_mort <- input_data[["cd4_mort_full"]]
input_data$art_mort <- input_data[["art_mort_full"]]

path <- write_standalone_data(input_data, name_mapping, "child_data.zip")
message(sprintf("Wrote child test data to %s", path))
