#' Generate C++ for passing output from model fit into R
#'
#' This generates using metadata from `src/model_outputs.yml`
#'
#' @param dest The destination to write generated code to.
#'
#' @return Nothing, called to generate code in src dir
#' @keywords internal
generate_build_r_output <- function(dest = file.path("src/model_output.hpp")) {
  template <- readLines(file.path("src/model_output.hpp.in"))
  outputs <- yaml::read_yaml(file.path("src/model_outputs.yml"))$outputs
  ## validate outputs have all required props

  for (i in seq_along(outputs)) {
    outputs[[i]]$dimensions <- parse_dimensions(outputs[[i]]$dimensions)
  }

  initialise_r_memory <- vcapply(outputs, generate_initialise_r_memory)
  initialise_r_memory <- paste(initialise_r_memory, collapse = "\n")
  set_r_dimensions <- vcapply(outputs, generate_set_r_dimensions)
  set_r_dimensions <- paste(set_r_dimensions, collapse = "\n")
  copy_data <- vcapply(outputs, generate_copy_data)
  copy_data <- paste(copy_data, collapse = "\n")
  return_output <- vcapply(outputs, generate_return)
  return_output <- paste0("return Rcpp::List::create(",
                          paste(return_output, collapse = ",\n"),
                          ");")
  header <- paste0(
    "// ========= DO NOT EDIT =========\n",
    "//This file is automatically generated. Do not edit this file. If you ",
    "want to make changes edit `model_output.hpp.in` and run ",
    "`./scripts/generate` to regenerate.")

  generated_code <- glue::glue(paste(template, collapse = "\n"),
                               .open = "{{", .close = "}}")
  writeLines(generated_code, dest)
  invisible(TRUE)
}

parse_dimensions <- function(dimensions) {
  vcapply(dimensions, function(dim) {
    if (dim != "output_years") {
      ## All other sizes are part of the state space struct
      dim <- paste0("ss.", dim)
    }
    dim
  })
}

generate_initialise_r_memory <- function(output) {
  dimensions <- paste(output$dimensions, collapse = " * ")
  sprintf("Rcpp::NumericVector r_%s(%s);", output$output_name, dimensions)
}

generate_set_r_dimensions <- function(output) {
  dimensions <- paste(output$dimensions, collapse = ", ")
  sprintf("r_%s.attr(\"dim\") = Rcpp::NumericVector::create(%s);",
          output$output_name, dimensions)
}

generate_copy_data <- function(output) {
  sprintf("std::copy_n(state.%s.data(), state.%s.size(), %s(r_%s));",
          output$state_name, output$state_name, output$r_type,
          output$output_name)
}

generate_return <- function(output) {
  dimensions <- paste(output$dimensions, collapse = ", ")
  sprintf("Rcpp::_[\"%s\"] = r_%s",
          output$output_name, output$output_name)
}
