# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_base_model <- function(data, projection_parameters, sim_years, hiv_steps_per_year, hiv_age_stratification = "full") {
    .Call(`_frogger_run_base_model`, data, projection_parameters, sim_years, hiv_steps_per_year, hiv_age_stratification)
}

