# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_base_model <- function(data, model_variant, time_steps, hiv_steps, save_steps, is_midyear_projection, t_ART_start) {
    .Call(`_frogger_run_base_model`, data, model_variant, time_steps, hiv_steps, save_steps, is_midyear_projection, t_ART_start)
}

