#!/bin/bash

set -e

## See https://stackoverflow.com/questions/10874308/how-to-use-google-perf-tools for some details of
## reading this output
./configure
make model_gprofile
CPUPROFILE="myprof.log" N_RUNS=1000 CPUPROFILE_FREQUENCY=1000 ./model_gprofile 60 10 data output
google-pprof --text ./model_gprofile myprof.log
google-pprof -web ./model_gprofile myprof.log
